export interface InsurancePage {
  slug: string;
  title: string;
  shortTitle: string;
  category: 'personal' | 'commercial' | 'property';
  tagline: string;
  description: string;
  icon: string;
  coverageTypes: { title: string; description: string }[];
  whoNeeds: { title: string; description: string }[];
  costFactors: string[];
  faqs: { question: string; answer: string }[];
  relatedSlugs: string[];
  seoTitle: string;
  seoDescription: string;
}

export const insurancePages: InsurancePage[] = [
  {
    slug: 'homeowners',
    title: "Homeowner's Insurance",
    shortTitle: "Homeowner's",
    category: 'personal',
    tagline: 'Bring the right coverage under your roof',
    description: "Homeowner's insurance provides financial protection for your home and personal belongings against risks like fire, theft, or natural disasters. It also covers liability if someone is injured on your property.",
    icon: 'home',
    coverageTypes: [
      { title: 'Dwelling Coverage', description: 'Protects your home structure from covered perils including fire, vandalism, and severe weather.' },
      { title: 'Personal Property Coverage', description: 'Covers your belongings like furniture, electronics, and clothing against theft, damage, or loss.' },
      { title: 'Liability Coverage', description: 'Financial protection if someone is injured on your property or you accidentally damage others\' property.' },
      { title: 'Additional Living Expenses', description: 'Covers temporary housing costs if your home becomes uninhabitable due to a covered event.' },
      { title: 'Medical Payments', description: 'Covers guest medical expenses on your property regardless of fault.' },
    ],
    whoNeeds: [
      { title: 'Residential Property Owners', description: 'Owners of houses, condominiums, and townhouses.' },
      { title: 'Rental Property Owners', description: 'Landlords who want to protect their investment properties.' },
      { title: 'Vacation Home Owners', description: 'Owners of secondary or seasonal residences.' },
    ],
    costFactors: [
      'Geographic location and natural disaster susceptibility',
      'Property value and replacement cost',
      'Home age, construction materials, and safety features',
      'Personal claims history',
      'Deductible and coverage limit choices',
    ],
    faqs: [
      { question: "What does homeowner's insurance cover?", answer: "Homeowner's insurance typically covers damage to your home's structure, personal property, liability for injuries on your property, and additional living expenses if your home becomes uninhabitable. Specific coverage depends on your policy terms." },
      { question: 'What types of homes are eligible?', answer: 'Single-family homes, townhouses, condos, mobile homes, new construction, and older homes can all be covered. Your agent can help find the right policy for your home type.' },
      { question: 'Does it cover natural disasters?', answer: 'Standard policies cover many perils, but certain natural disasters like floods and earthquakes typically require separate coverage. Speak with an agent about your specific risks.' },
      { question: 'Do I need insurance if my home is paid off?', answer: "While it's not legally required if you don't have a mortgage, homeowner's insurance is strongly recommended to protect your investment and provide liability coverage." },
    ],
    relatedSlugs: ['rental-dwelling', 'short-term-rental', 'builders-risk'],
    seoTitle: "Homeowners Insurance in North Carolina — Get a Free Quote",
    seoDescription: "Homeowners insurance in North Carolina from BlackArrow Insurance. We compare rates from 20+ carriers to protect your NC home, including coastal and wind/hail coverage. Free quote.",
  },
  {
    slug: 'auto',
    title: 'Auto Insurance',
    shortTitle: 'Auto',
    category: 'personal',
    tagline: 'The right coverage to seize the road ahead',
    description: 'Auto insurance provides financial protection for your vehicle and covers damages from accidents, theft, or natural events. It also includes liability coverage to protect you financially if you cause injury or damage to others.',
    icon: 'car',
    coverageTypes: [
      { title: 'Liability Coverage', description: 'Covers bodily injury and property damage you cause to others in an accident.' },
      { title: 'Collision Coverage', description: 'Pays for damage to your vehicle from collisions with other vehicles or objects.' },
      { title: 'Comprehensive Coverage', description: 'Protects against non-collision events like theft, vandalism, and natural disasters.' },
      { title: 'Uninsured/Underinsured Motorist', description: 'Protects you when the other driver lacks sufficient insurance coverage.' },
      { title: 'Medical Payments (MedPay)', description: 'Covers medical expenses for you and your passengers after an accident.' },
      { title: 'Personal Injury Protection (PIP)', description: 'Covers medical costs, wage loss, and injury-related expenses regardless of fault.' },
    ],
    whoNeeds: [
      { title: 'Personal Vehicle Owners', description: 'Anyone who owns and operates a personal vehicle on public roads.' },
      { title: 'Commercial Fleet Businesses', description: 'Businesses that use vehicles for commercial operations.' },
      { title: 'Rideshare & Delivery Drivers', description: 'Drivers who use their vehicles for ride-sharing or delivery services.' },
    ],
    costFactors: [
      'Driving history and record',
      'Vehicle type, age, make, and model',
      'Geographic location and weather risk',
      'Usage patterns and annual mileage',
      'Selected coverage limits and deductibles',
      'Credit history',
    ],
    faqs: [
      { question: 'What types of auto insurance coverage are available?', answer: 'Auto insurance includes liability, collision, comprehensive, uninsured/underinsured motorist, medical payments, and personal injury protection. Your agent can customize a policy with the right mix for you.' },
      { question: 'Is auto insurance required by law?', answer: 'Most states require minimum liability coverage. Requirements vary by state, so speak with an agent to ensure you meet your state\'s requirements.' },
      { question: 'Does my policy cover rental cars?', answer: 'Many auto insurance policies extend coverage to rental vehicles. Check with your agent to confirm your specific policy details.' },
      { question: 'How are premiums calculated?', answer: 'Premiums are based on factors including your driving record, vehicle type, location, coverage levels, and deductible choices.' },
    ],
    relatedSlugs: ['commercial-auto', 'dump-straight-truck', 'boat'],
    seoTitle: 'Auto Insurance in North Carolina — Compare NC Car Insurance Rates',
    seoDescription: 'Affordable auto insurance in North Carolina from BlackArrow Insurance. Compare NC car insurance rates from 20+ carriers for liability, collision, and full coverage. Free quote.',
  },
  {
    slug: 'life',
    title: 'Life Insurance',
    shortTitle: 'Life',
    category: 'personal',
    tagline: 'Personalized plans for more peace of mind',
    description: 'Life insurance provides financial protection for your loved ones by offering a death benefit to help cover expenses, replace lost income, or secure their financial future.',
    icon: 'heart',
    coverageTypes: [
      { title: 'Term Life Insurance', description: 'Provides coverage for a specified period, such as 10, 20, or 30 years, with lower premiums. Ideal for temporary coverage needs.' },
      { title: 'Whole Life Insurance', description: 'Lifetime coverage with fixed premiums and a growing cash value component that you can borrow against.' },
      { title: 'Universal Life Insurance', description: 'Flexible premiums with an interest-earning cash value component, offering more control over your policy.' },
      { title: 'Final Expense Insurance', description: 'Designed to cover end-of-life expenses and funeral costs, providing peace of mind for your family.' },
    ],
    whoNeeds: [
      { title: 'Individuals & Families', description: 'Replace lost income, cover final expenses, and support dependents in the event of your passing.' },
      { title: 'Business Owners', description: 'Fund buy-sell agreements and ensure business continuity.' },
      { title: 'Estate Planning', description: 'Cover estate taxes and protect inheritance for your beneficiaries.' },
    ],
    costFactors: [
      'Age — younger applicants typically receive lower premiums',
      'Health status and family medical history',
      'Smoking status and lifestyle habits',
      'Coverage amount and policy type',
      'Occupation and high-risk hobbies',
      'Length of coverage term',
    ],
    faqs: [
      { question: 'Why do I need life insurance?', answer: 'Life insurance is essential for anyone with dependents or financial obligations. It ensures your loved ones are financially secure in the event of your passing.' },
      { question: 'What are the different types of life insurance?', answer: 'The two primary categories are term life (coverage for a specific period) and permanent life (whole life and universal life with cash value components).' },
      { question: 'How much life insurance do I need?', answer: 'A common rule of thumb is to have coverage that is 10 to 15 times your annual income, adjusted for outstanding debts and future financial needs.' },
      { question: 'Can I modify my life insurance policy?', answer: 'Yes, many policies allow adjustments to coverage amounts, addition of riders, or conversion between policy types. Changes may affect your premiums.' },
    ],
    relatedSlugs: ['homeowners', 'auto', 'boat'],
    seoTitle: 'Life Insurance in North Carolina — Term, Whole & Universal',
    seoDescription: 'Protect your family\'s financial future with personalized life insurance from BlackArrow Insurance. Term, whole life, and universal options available.',
  },
  {
    slug: 'boat',
    title: 'Boat Insurance',
    shortTitle: 'Boat',
    category: 'personal',
    tagline: 'Personalized plans for more peace of mind',
    description: 'Boat insurance provides financial protection for your vessel, covering damages from accidents, theft, or natural events. It also includes liability coverage to protect you on the water.',
    icon: 'anchor',
    coverageTypes: [
      { title: 'Liability Coverage', description: 'Covers injuries or property damage caused to others while operating your boat.' },
      { title: 'Comprehensive Coverage', description: 'Protection against theft, vandalism, and natural events when your boat is not in use.' },
      { title: 'Collision Coverage', description: 'Covers repair or replacement costs from collisions with other vessels or objects.' },
      { title: 'Uninsured/Underinsured Boater', description: 'Protects you in an accident when the other party lacks sufficient insurance.' },
      { title: 'Medical Payments', description: 'Covers medical expenses for you, your passengers, or others injured in a boating incident.' },
      { title: 'Towing & Assistance', description: 'Covers breakdown support and towing services on the water.' },
    ],
    whoNeeds: [
      { title: 'Personal Boat Owners', description: 'Recreational boaters seeking comprehensive vessel protection.' },
      { title: 'Commercial Vessel Operators', description: 'Businesses that operate boats for commercial purposes.' },
      { title: 'Charter & Rental Companies', description: 'Companies that rent or charter boats to customers.' },
    ],
    costFactors: [
      'Boat type, size, and value',
      'Usage patterns and geographic location',
      'Coverage types and limits selected',
      'Safety equipment and training certifications',
      'Claims history',
    ],
    faqs: [
      { question: 'Is boat insurance required?', answer: 'While not legally mandated in all states, boat insurance is highly recommended and may be required by your marina or lender.' },
      { question: 'Does it cover my boat trailer?', answer: 'Trailer coverage is typically available as an addition to your boat insurance policy. Ask your agent for details.' },
      { question: 'Am I covered during transport?', answer: 'Transportation damage coverage varies by provider. Many policies can include coverage while your boat is being towed or transported.' },
      { question: 'Do I need coverage year-round?', answer: 'Year-round coverage is recommended even for seasonal boats, as risks like theft and weather damage exist even when your boat is in storage.' },
    ],
    relatedSlugs: ['auto', 'homeowners', 'life'],
    seoTitle: 'Boat Insurance in North Carolina — Wilmington & Coastal NC',
    seoDescription: 'Protect your vessel with comprehensive boat insurance from BlackArrow Insurance. Get coverage for accidents, theft, liability, and more.',
  },
  {
    slug: 'rental-dwelling',
    title: 'Rental Dwelling Insurance in North Carolina',
    shortTitle: 'Rental Dwelling',
    category: 'property',
    tagline: 'Protect your North Carolina rental property',
    description: 'Rental dwelling insurance for North Carolina landlords. BlackArrow serves rental property owners across Eastern NC — Greenville, Whiteville, Wilmington, Raleigh, and the surrounding Columbus, Pitt, and Brunswick counties — with coverage for fire, storm, theft, vandalism, lost rental income, and tenant-liability claims.',
    icon: 'building',
    coverageTypes: [
      { title: 'Property Damage Coverage', description: 'Covers structural damage from fire, vandalism, hurricanes, and severe weather common to Eastern North Carolina.' },
      { title: 'Liability Coverage', description: 'Covers medical expenses and legal fees for tenant or visitor injuries on your NC rental property.' },
      { title: 'Loss of Rental Income', description: 'Compensation during periods when your property is uninhabitable due to a covered event — critical in NC\'s hurricane-exposed coastal counties.' },
      { title: 'Personal Property Coverage', description: 'Covers landlord-owned items like appliances and furnishings in the rental unit.' },
      { title: 'Vandalism & Theft Coverage', description: 'Protection against tenant-caused damage or theft of property.' },
    ],
    whoNeeds: [
      { title: 'Individual NC Landlords', description: 'Owners renting single-family homes or apartment units in Eastern North Carolina.' },
      { title: 'Property Management Companies', description: 'Companies overseeing multiple rental units across NC.' },
      { title: 'Real Estate Investors', description: 'Investors protecting their North Carolina rental property portfolio.' },
    ],
    costFactors: [
      'Property location — coastal NC counties price higher due to hurricane exposure',
      'Property value and age',
      'Coverage types and limits selected',
      'Safety features like security systems and smoke alarms',
      'Claims history',
    ],
    faqs: [
      { question: 'Does BlackArrow offer rental dwelling insurance outside North Carolina?', answer: 'No. BlackArrow is an independent brokerage serving Eastern North Carolina specifically — Greenville, Whiteville, Wilmington, Raleigh, and surrounding areas. If you\'re looking for rental dwelling coverage outside NC, we recommend contacting an agency licensed in your state.' },
      { question: 'Do I need separate insurance for my NC rental property?', answer: 'Yes — standard homeowner\'s insurance typically does not cover rental activities. A rental dwelling policy provides the specific protections NC landlords need.' },
      { question: 'Does it cover tenant belongings?', answer: 'No, rental dwelling insurance covers the structure and landlord-owned property. Tenants need their own renters insurance for personal belongings.' },
      { question: 'How can I lower my premiums?', answer: 'You can lower premiums by choosing higher deductibles, installing safety features (especially storm-resilient roofing in coastal NC), bundling policies, and maintaining a good claims history.' },
    ],
    relatedSlugs: ['short-term-rental', 'long-term-rental', 'homeowners'],
    seoTitle: 'Rental Dwelling Insurance in North Carolina — Landlord Coverage',
    seoDescription: 'Rental property insurance for North Carolina landlords. BlackArrow Insurance serves Eastern NC — Greenville, Whiteville, Wilmington, Raleigh. Protection against storm damage, liability, and lost rental income.',
  },
  {
    slug: 'dump-straight-truck',
    title: 'Dump & Straight Truck Insurance',
    shortTitle: 'Dump & Straight Truck',
    category: 'commercial',
    tagline: 'Specialized coverage for your heavy-duty fleet',
    description: 'Dump and straight truck insurance provides financial protection for your commercial vehicles, covering damages from accidents, theft, or unexpected events on the road.',
    icon: 'cube',
    coverageTypes: [
      { title: 'Liability Coverage', description: 'Covers injury and property damage you cause to others while operating your truck.' },
      { title: 'Physical Damage Coverage', description: 'Collision and comprehensive protection for your vehicle.' },
      { title: 'Cargo Coverage', description: 'Protects the goods and materials being transported.' },
      { title: 'Uninsured/Underinsured Motorist', description: 'Protection against drivers who lack sufficient insurance.' },
      { title: 'Medical Payments', description: 'Covers accident-related medical expenses for you and passengers.' },
      { title: 'Downtime & Rental Reimbursement', description: 'Lost income support while your truck is being repaired.' },
    ],
    whoNeeds: [
      { title: 'Independent Owner-Operators', description: 'Individuals managing their own dump or straight trucks.' },
      { title: 'Construction & Contracting Companies', description: 'Businesses operating fleets of heavy-duty vehicles.' },
      { title: 'Fleet Managers & Logistics Providers', description: 'Companies overseeing multiple commercial trucks.' },
    ],
    costFactors: [
      'Truck type and usage patterns',
      'Cargo classification and value',
      'Geographic location and annual mileage',
      'Driver records and safety training',
      'Coverage limits and deductible amounts',
    ],
    faqs: [
      { question: 'Can I customize my dump truck insurance?', answer: 'Yes, many providers allow businesses to customize their dump and straight truck insurance policies to fit their unique operational needs.' },
      { question: 'Does it cover my employees?', answer: 'Policies typically cover authorized employees, pending the insurance company\'s driver requirements and approval.' },
      { question: 'What coverage types are included?', answer: 'Standard options include liability, physical damage, cargo, and uninsured motorist coverage. Additional options are available.' },
    ],
    relatedSlugs: ['commercial-auto', 'equipment', 'general-liability'],
    seoTitle: 'Dump & Straight Truck Insurance in North Carolina',
    seoDescription: 'Get specialized dump truck and straight truck insurance from BlackArrow Insurance. Protect your fleet with comprehensive commercial coverage.',
  },
  {
    slug: 'commercial-auto',
    title: 'Commercial Auto Insurance',
    shortTitle: 'Commercial Auto',
    category: 'commercial',
    tagline: 'Keep your business moving with confidence',
    description: 'Commercial auto insurance provides financial protection for your business vehicles, covering damages from accidents, theft, or unexpected incidents on the road.',
    icon: 'clipboard-check',
    coverageTypes: [
      { title: 'Liability Coverage', description: 'Covers bodily injury and property damage you cause to others with your business vehicle.' },
      { title: 'Physical Damage Coverage', description: 'Collision and comprehensive protection for your commercial vehicles.' },
      { title: 'Cargo Coverage', description: 'Protects the goods being transported by your vehicles.' },
      { title: 'Uninsured/Underinsured Motorist', description: 'Protection when the other driver lacks adequate coverage.' },
      { title: 'Medical Payments', description: 'Covers accident-related medical expenses.' },
      { title: 'Rental Reimbursement & Downtime', description: 'Covers costs while your vehicle is out of service for repairs.' },
    ],
    whoNeeds: [
      { title: 'Independent Contractors', description: 'Owner-operators who use vehicles for business.' },
      { title: 'Delivery & Logistics Companies', description: 'Businesses that transport goods to customers.' },
      { title: 'Trades & Service Providers', description: 'Electricians, plumbers, and other professionals who drive to job sites.' },
    ],
    costFactors: [
      'Vehicle type and usage',
      'Driving distance and routes',
      'Driver history and training',
      'Coverage limits and deductibles',
    ],
    faqs: [
      { question: 'Who needs commercial auto insurance?', answer: 'Any business that uses vehicles for commercial purposes, including deliveries, transporting equipment, or driving to client locations.' },
      { question: 'What types of coverage are included?', answer: 'Policies include liability, physical damage, cargo, uninsured motorist, medical payments, and rental reimbursement.' },
      { question: 'Does it cover personal vehicle use?', answer: 'Commercial policies typically cover business use. Personal auto insurance covers personal driving. Your agent can help determine the right coverage mix.' },
      { question: 'Can policies be customized?', answer: 'Yes, commercial auto policies can be tailored to match your specific fleet, drivers, and business operations.' },
    ],
    relatedSlugs: ['dump-straight-truck', 'general-liability', 'business-owners-package'],
    seoTitle: 'Commercial Auto Insurance in North Carolina — NC Fleet Coverage',
    seoDescription: 'Protect your business vehicles with commercial auto insurance from BlackArrow Insurance. Customized fleet coverage with competitive rates.',
  },
  {
    slug: 'general-liability',
    title: 'General Liability Insurance',
    shortTitle: 'General Liability',
    category: 'commercial',
    tagline: 'Essential protection for every business',
    description: 'General liability insurance provides essential financial protection for your business, covering expenses related to third-party injuries, property damage, and legal claims.',
    icon: 'shield',
    coverageTypes: [
      { title: 'Bodily Injury Liability', description: 'Covers medical expenses and legal fees if someone is injured on your business premises or due to your operations.' },
      { title: 'Property Damage Liability', description: 'Protection when your business operations cause damage to others\' property.' },
      { title: 'Personal & Advertising Injury', description: 'Covers claims related to defamation, slander, or copyright infringement, protecting your business reputation.' },
      { title: 'Medical Payments', description: 'Pays for minor injuries on your premises, regardless of fault.' },
      { title: 'Products & Completed Operations', description: 'Coverage for injury or damage caused by your products or services after delivery or completion.' },
    ],
    whoNeeds: [
      { title: 'Small Business Owners', description: 'Any small business that interacts with customers or the public.' },
      { title: 'Contractors & Service Providers', description: 'Businesses that work on client properties or job sites.' },
      { title: 'Retailers & Restaurants', description: 'Businesses with physical locations that welcome customers.' },
    ],
    costFactors: [
      'Business size and industry risk level',
      'Location and premises exposure',
      'Coverage limits and deductibles',
      'Claims history',
    ],
    faqs: [
      { question: 'Does general liability cover employee injuries?', answer: 'No, general liability insurance does not cover employee injuries. You need workers\' compensation insurance for that.' },
      { question: 'What\'s the difference between general and professional liability?', answer: 'General liability covers third-party bodily injury and property damage. Professional liability covers negligence and errors in your professional services.' },
      { question: 'How much coverage does my business need?', answer: 'Coverage needs vary by industry and risk level. Most small businesses start with $1 million per occurrence. Your agent can help determine the right amount.' },
    ],
    relatedSlugs: ['business-owners-package', 'workers-compensation', 'cyber-liability'],
    seoTitle: 'General Liability Insurance in North Carolina for Small Business',
    seoDescription: 'Protect your business from third-party claims with general liability insurance from BlackArrow Insurance. Get a quote today.',
  },
  {
    slug: 'cyber-liability',
    title: 'Cyber Liability Insurance',
    shortTitle: 'Cyber Liability',
    category: 'commercial',
    tagline: 'Defend your business in the digital age',
    description: 'Cyber liability insurance covers expenses related to data loss, cyberattacks, and legal claims stemming from a security incident, helping you manage digital risks.',
    icon: 'lock',
    coverageTypes: [
      { title: 'Data Breach Coverage', description: 'Covers notification costs, credit monitoring, and legal fees following a data breach.' },
      { title: 'Network Security Liability', description: 'Protection against claims from unauthorized access to your network.' },
      { title: 'Business Interruption', description: 'Covers lost income when a cyber event disrupts your business operations.' },
      { title: 'Regulatory Fines & Penalties', description: 'Covers compliance-related costs and regulatory penalties after a breach.' },
      { title: 'Media Liability', description: 'Protection against copyright infringement and defamation claims related to digital content.' },
    ],
    whoNeeds: [
      { title: 'Small & Medium Enterprises', description: 'Businesses of all sizes that store customer data digitally.' },
      { title: 'E-Commerce Businesses', description: 'Online retailers that handle payment and customer information.' },
      { title: 'Healthcare Providers', description: 'Organizations handling sensitive patient health information.' },
    ],
    costFactors: [
      'Business size and industry',
      'Data security measures in place',
      'Claims history',
      'Coverage limits and deductibles',
    ],
    faqs: [
      { question: 'What does cyber liability insurance cover?', answer: 'It covers data breach costs, legal defense, PR expenses, regulatory penalties, business interruption, and notification costs following a cyber incident.' },
      { question: 'What isn\'t covered?', answer: 'Typically excludes data restoration from system failures, negligence-caused incidents, and pre-existing known vulnerabilities.' },
      { question: 'What cyber incidents are commonly covered?', answer: 'Data breaches, ransomware attacks, denial-of-service attacks, and unauthorized network access are commonly covered events.' },
    ],
    relatedSlugs: ['general-liability', 'business-owners-package', 'equipment'],
    seoTitle: 'Cyber Liability Insurance in North Carolina for Small Business',
    seoDescription: 'Protect your business from cyber threats with cyber liability insurance from BlackArrow Insurance. Coverage for data breaches, ransomware, and more.',
  },
  {
    slug: 'equipment',
    title: 'Equipment Insurance',
    shortTitle: 'Equipment',
    category: 'commercial',
    tagline: 'Protect the tools that power your business',
    description: 'Equipment insurance provides essential coverage for your business assets, protecting against damages or losses due to accidents, theft, or unexpected events.',
    icon: 'wrench',
    coverageTypes: [
      { title: 'Property Damage Coverage', description: 'Covers repair or replacement costs for damaged or stolen equipment.' },
      { title: 'Equipment Breakdown Coverage', description: 'Protects against repair costs associated with mechanical or electrical equipment failures.' },
      { title: 'Loss of Income Coverage', description: 'Offers financial support for lost revenue if equipment failure disrupts business operations.' },
      { title: 'Rental Equipment Coverage', description: 'Provides protection for equipment that you rent or lease for business use.' },
    ],
    whoNeeds: [
      { title: 'Construction Companies', description: 'Businesses that rely on heavy machinery and specialized tools.' },
      { title: 'Manufacturers', description: 'Companies with expensive production equipment and machinery.' },
      { title: 'Event Planners & Rental Services', description: 'Businesses that own or rent specialized equipment for events.' },
    ],
    costFactors: [
      'Type and value of equipment',
      'Usage patterns and location',
      'Coverage limits and deductibles',
      'Claims history',
    ],
    faqs: [
      { question: 'What types of equipment are covered?', answer: 'Coverage includes construction machinery, tools, computers, printers, medical equipment, and specialized industry tools.' },
      { question: 'How does the claims process work?', answer: 'You file a claim with documentation of the loss. Your insurer assesses the damage and determines compensation based on policy terms.' },
      { question: 'What are common exclusions?', answer: 'Wear and tear, intentional damage, equipment used for illegal activities, and damage from lack of proper maintenance are typically excluded.' },
      { question: 'Is equipment insurance required?', answer: 'While not legally mandated, it\'s highly recommended for businesses that rely on expensive equipment.' },
    ],
    relatedSlugs: ['commercial-property', 'business-owners-package', 'general-liability'],
    seoTitle: 'Equipment Insurance in North Carolina — Tools & Machinery Coverage',
    seoDescription: 'Protect your business equipment from damage, theft, and breakdown with equipment insurance from BlackArrow Insurance.',
  },
  {
    slug: 'business-owners-package',
    title: "Business Owner's Package (BOP)",
    shortTitle: 'BOP',
    category: 'commercial',
    tagline: 'Comprehensive coverage in one smart package',
    description: "A Business Owner's Package combines essential coverages to protect small and medium-sized businesses from common risks, all in one convenient policy. This package typically includes general liability, property insurance, and business interruption coverage.",
    icon: 'briefcase',
    coverageTypes: [
      { title: 'General Liability Insurance', description: 'Protects against bodily injury, property damage, or personal injury claims occurring on your premises or during operations.' },
      { title: 'Property Insurance', description: 'Covers your buildings, inventory, and equipment against damage from fire, theft, or vandalism.' },
      { title: 'Business Interruption Insurance', description: 'Replaces lost income and covers operating expenses during forced closures from covered events.' },
      { title: 'Professional Liability (Optional)', description: 'Addresses negligence or service delivery mistakes in your professional services.' },
      { title: 'Cyber Liability (Optional)', description: 'Protects against data breaches and cyberattacks targeting your business.' },
    ],
    whoNeeds: [
      { title: 'Retailers', description: 'Clothing shops, furniture stores, and other retail establishments.' },
      { title: 'Restaurants & Cafes', description: 'Food service businesses with physical locations.' },
      { title: 'Service Providers', description: 'Plumbers, electricians, marketing consultants, and similar professionals.' },
      { title: 'Contractors & Consultants', description: 'Independent professionals who need bundled protection.' },
    ],
    costFactors: [
      'Type of business and industry',
      'Size of operation and number of employees',
      'Value of business assets and property',
      'Coverage levels needed',
    ],
    faqs: [
      { question: 'What does a BOP include?', answer: 'A standard BOP usually includes general liability, commercial property, and business interruption coverage, with optional add-ons for professional liability and cyber coverage.' },
      { question: 'How much does a BOP cost?', answer: 'Cost depends on business type, size, property value, and selected limits. A BOP is typically more cost-effective than purchasing separate policies.' },
      { question: 'Which businesses benefit most from a BOP?', answer: 'Small and medium-sized businesses in retail, restaurants, and service industries benefit most from the bundled coverage.' },
      { question: 'How do I know if a BOP is right for my business?', answer: 'If you have property to protect, liability exposure, or income risk and prefer consolidated coverage, a BOP may be ideal. Speak with an agent for guidance.' },
    ],
    relatedSlugs: ['general-liability', 'commercial-property', 'workers-compensation'],
    seoTitle: "Business Owner's Package (BOP) Insurance in North Carolina",
    seoDescription: "Get comprehensive business protection with a Business Owner's Package from BlackArrow Insurance. Bundled coverage at competitive rates.",
  },
  {
    slug: 'workers-compensation',
    title: "Worker's Compensation Insurance",
    shortTitle: "Worker's Comp",
    category: 'commercial',
    tagline: 'Protect your team and your business',
    description: "Worker's compensation insurance provides essential coverage for your employees, protecting them in case of work-related injuries or illnesses. It covers medical expenses, lost wages, and rehabilitation costs.",
    icon: 'users',
    coverageTypes: [
      { title: 'Medical Expenses Coverage', description: 'Covers all treatment related to work injuries and illnesses, including hospital visits, surgeries, and medications.' },
      { title: 'Lost Wages & Disability Benefits', description: 'Provides partial wage replacement during recovery from a work-related injury.' },
      { title: 'Rehabilitation & Vocational Training', description: 'Covers physical therapy and return-to-work services, including job retraining if needed.' },
      { title: 'Death Benefits', description: 'Provides financial support for families following fatal workplace injuries or illnesses.' },
    ],
    whoNeeds: [
      { title: 'Construction Companies', description: 'High-risk industry with significant workplace injury potential.' },
      { title: 'Manufacturing Businesses', description: 'Companies with workers operating heavy machinery.' },
      { title: 'Healthcare Providers', description: 'Organizations with staff exposed to workplace hazards.' },
    ],
    costFactors: [
      'Industry risk classification',
      'Claims history and experience rating',
      'Payroll and employee classifications',
      'Coverage limits and deductibles',
    ],
    faqs: [
      { question: 'What injuries are covered?', answer: "Work-related accidents, repetitive motion injuries, and occupational illnesses are covered. Coverage generally excludes injuries from intoxication, horseplay, or self-inflicted harm." },
      { question: 'How is the cost determined?', answer: 'Multiple factors including business type, job risk levels, number of employees, payroll, and claims history influence premium costs.' },
      { question: 'Are part-time employees covered?', answer: 'Generally yes. Most states require coverage for all employees, including part-time and seasonal workers.' },
      { question: 'What happens if I don\'t have coverage?', answer: 'Businesses without required coverage may face penalties, fines, legal action, and direct liability for all employee medical costs.' },
    ],
    relatedSlugs: ['general-liability', 'business-owners-package', 'commercial-property'],
    seoTitle: "Workers Compensation Insurance in North Carolina",
    seoDescription: "Protect your employees with worker's compensation insurance from BlackArrow Insurance. Coverage for injuries, lost wages, and rehabilitation.",
  },
  {
    slug: 'commercial-property',
    title: 'Commercial Property Insurance',
    shortTitle: 'Commercial Property',
    category: 'commercial',
    tagline: 'Safeguard your business assets',
    description: 'Commercial property insurance protects your business\'s physical assets, including buildings, equipment, and inventory, against damage from events like fire, theft, and natural disasters.',
    icon: 'building2',
    coverageTypes: [
      { title: 'Building Coverage', description: 'Structural protection against fire, storms, vandalism, and other covered perils.' },
      { title: 'Contents Coverage', description: 'Covers equipment, furniture, inventory, and other business property inside your building.' },
      { title: 'Business Interruption', description: 'Income replacement and expense coverage during periods of operational disruption.' },
      { title: 'Equipment Breakdown', description: 'Covers mechanical and electrical failures of business equipment.' },
    ],
    whoNeeds: [
      { title: 'Retail & Hospitality', description: 'Stores, restaurants, and hotels with physical locations and inventory.' },
      { title: 'Manufacturing & Warehousing', description: 'Businesses with large facilities and valuable equipment.' },
      { title: 'Professional Offices', description: 'Office-based businesses with equipment and furnishings to protect.' },
    ],
    costFactors: [
      'Location and building type',
      'Industry and contents value',
      'Security and safety measures (fire alarms, sprinklers, cameras)',
      'Coverage limits and deductibles',
    ],
    faqs: [
      { question: 'Do small businesses need commercial property insurance?', answer: 'Yes, any business with physical assets to protect should consider commercial property insurance, regardless of size.' },
      { question: 'Does it cover natural disasters?', answer: 'Standard policies cover many perils, but floods and earthquakes often require separate coverage. Your agent can review your specific risks.' },
      { question: 'Is equipment breakdown included?', answer: 'Equipment breakdown can typically be added to your policy. It covers mechanical and electrical failures of business equipment.' },
      { question: 'Do I need coverage if I lease my space?', answer: 'Yes, even if you lease, you may need coverage for your contents, business equipment, and improvements made to the space.' },
    ],
    relatedSlugs: ['business-owners-package', 'equipment', 'general-liability'],
    seoTitle: 'Commercial Property Insurance in North Carolina',
    seoDescription: 'Protect your business property with comprehensive commercial property insurance from BlackArrow Insurance. Buildings, equipment, and inventory coverage.',
  },
  {
    slug: 'short-term-rental',
    title: 'Short Term Rental Insurance',
    shortTitle: 'Short Term Rental',
    category: 'property',
    tagline: 'Protect your rental income and property',
    description: 'Short term rental insurance provides essential protection for property owners, covering potential damages, liability claims, and income loss that may arise from guest stays.',
    icon: 'key',
    coverageTypes: [
      { title: 'Property Damage Coverage', description: 'Covers repair or replacement costs for damage caused by guests, whether accidental or from negligence.' },
      { title: 'Liability Coverage', description: 'Protects you against claims if a guest is injured on your property.' },
      { title: 'Loss of Income Coverage', description: 'Financial support if your property becomes uninhabitable and you lose rental income.' },
      { title: 'Contents Coverage', description: 'Protection for personal items, furnishings, and amenities in your rental property.' },
    ],
    whoNeeds: [
      { title: 'Vacation Rental Hosts', description: 'Airbnb, VRBO, and other platform hosts.' },
      { title: 'Landlords with Short-Term Tenants', description: 'Property owners offering temporary rental arrangements.' },
      { title: 'Property Management Companies', description: 'Companies managing multiple short-term rental properties.' },
    ],
    costFactors: [
      'Property type and location',
      'Frequency of rentals',
      'Coverage limits and deductibles',
      'Amenities provided (pools, hot tubs, recreational equipment)',
    ],
    faqs: [
      { question: 'Does it cover guest-caused damages?', answer: 'Yes, short-term rental insurance generally includes coverage for damages caused by guests, whether accidental or due to negligence.' },
      { question: 'What if a guest is injured?', answer: 'Your liability coverage protects you if a guest is injured on your property, covering medical expenses and legal costs.' },
      { question: 'Is rental income protected during repairs?', answer: 'Many policies include loss of income coverage to compensate for rental income lost while your property is being repaired.' },
      { question: 'Is short-term rental insurance legally required?', answer: 'While not always legally required, many rental platforms strongly recommend it, and it\'s essential for protecting your investment.' },
    ],
    relatedSlugs: ['long-term-rental', 'rental-dwelling', 'homeowners'],
    seoTitle: 'Short Term Rental Insurance in North Carolina — Airbnb & VRBO',
    seoDescription: 'Protect your Airbnb or vacation rental with short term rental insurance from BlackArrow Insurance. Coverage for damages, liability, and lost income.',
  },
  {
    slug: 'long-term-rental',
    title: 'Long Term Rental Insurance',
    shortTitle: 'Long Term Rental',
    category: 'property',
    tagline: 'Protect your long-term rental investment',
    description: 'Long term rental insurance provides crucial protection for property owners, covering risks such as property damage, tenant-caused loss, and liability for residential rental properties.',
    icon: 'home',
    coverageTypes: [
      { title: 'Property Damage Coverage', description: 'Covers repairs or replacement from disasters, vandalism, and tenant-caused damage.' },
      { title: 'Liability Coverage', description: 'Medical costs and legal expenses for tenant or visitor injuries on your property.' },
      { title: 'Loss of Rental Income', description: 'Compensation if your property becomes uninhabitable due to a covered event.' },
      { title: 'Tenant Default Protection', description: 'Protection against unpaid rent or early lease abandonment by tenants.' },
    ],
    whoNeeds: [
      { title: 'Residential Landlords', description: 'Owners of single or multi-family rental properties.' },
      { title: 'Multi-Family Unit Owners', description: 'Investors with apartment buildings or duplexes.' },
      { title: 'Property Managers', description: 'Professional managers overseeing rental portfolios.' },
    ],
    costFactors: [
      'Property value and location',
      'Coverage limits and deductibles',
      'Tenant type and lease terms',
      'Claims history',
    ],
    faqs: [
      { question: 'Are tenant damages covered?', answer: 'Yes, tenant-caused damages are typically covered, excluding normal wear and tear.' },
      { question: 'How is it different from homeowner\'s insurance?', answer: 'Long-term rental insurance is specifically designed for rental properties and covers risks unique to landlords that homeowner\'s insurance doesn\'t.' },
      { question: 'Is loss of rental income included?', answer: 'Yes, most policies include coverage for lost rental income when your property can\'t be occupied due to a covered event.' },
      { question: 'Are tenant belongings covered?', answer: 'No, tenants need their own renters insurance for personal belongings. Your policy covers the structure and your property.' },
    ],
    relatedSlugs: ['short-term-rental', 'rental-dwelling', 'vacant-unoccupied'],
    seoTitle: 'Long Term Rental Property Insurance in North Carolina',
    seoDescription: 'Protect your long-term rental property with comprehensive insurance from BlackArrow Insurance. Coverage for damage, liability, and lost income.',
  },
  {
    slug: 'builders-risk',
    title: "Builder's Risk Insurance",
    shortTitle: "Builder's Risk",
    category: 'property',
    tagline: 'Coverage for every stage of construction',
    description: "Builder's risk insurance provides crucial coverage for construction projects, protecting against potential damages or losses due to accidents, theft, vandalism, or unforeseen events.",
    icon: 'hardhat',
    coverageTypes: [
      { title: 'Property Damage Coverage', description: 'Covers physical damage from fire, storms, and vandalism during construction.' },
      { title: 'Theft & Vandalism Coverage', description: 'Protects construction materials and equipment from theft and intentional damage.' },
      { title: 'Weather-Related Damage', description: 'Coverage for wind, hail, flooding, and other weather-related damage to construction projects.' },
      { title: 'Tools & Equipment Coverage', description: 'Covers on-site machinery and tools for repair or replacement.' },
    ],
    whoNeeds: [
      { title: 'General Contractors', description: 'Protection against fire, storms, and theft of materials on job sites.' },
      { title: 'Property Owners', description: 'Investors safeguarding their investment during renovations or new builds.' },
      { title: 'Subcontractors', description: 'Coverage for specific work and materials contributed to a project.' },
    ],
    costFactors: [
      'Project size and scope',
      'Geographic location (severe weather, crime rates)',
      'Construction timeline duration',
      'Type of construction materials used',
    ],
    faqs: [
      { question: 'Who needs builder\'s risk insurance?', answer: 'Property owners, contractors, subcontractors, and project lenders should all consider builder\'s risk coverage for construction projects.' },
      { question: 'What does it cover?', answer: 'It typically covers damages to the building under construction, construction materials, and equipment on-site, including fire, theft, vandalism, and weather damage.' },
      { question: 'Does it cover worker injuries?', answer: 'No, worker injuries require workers\' compensation or general liability insurance. Builder\'s risk covers property and materials.' },
      { question: 'How long does coverage last?', answer: 'Coverage is effective for the construction period and may require renewal if the project extends beyond the original timeline.' },
    ],
    relatedSlugs: ['commercial-property', 'vacant-unoccupied', 'general-liability'],
    seoTitle: "Builder's Risk Insurance in North Carolina — Construction Coverage",
    seoDescription: "Protect your construction project with builder's risk insurance from BlackArrow Insurance. Coverage for materials, equipment, and property damage.",
  },
  {
    slug: 'vacant-unoccupied',
    title: 'Vacant / Unoccupied Insurance',
    shortTitle: 'Vacant / Unoccupied',
    category: 'property',
    tagline: 'Protection for properties between occupants',
    description: 'Vacant and unoccupied insurance provides crucial protection for properties that are temporarily uninhabited, covering risks such as theft, vandalism, and damage from unexpected events.',
    icon: 'building',
    coverageTypes: [
      { title: 'Property Damage Coverage', description: 'Covers damage from fire, storms, vandalism, and theft for unoccupied properties.' },
      { title: 'Liability Coverage', description: 'Injury protection for unauthorized visitors or trespassers on your vacant property.' },
      { title: 'Loss of Rent Coverage', description: 'Income replacement during vacancy periods if applicable.' },
    ],
    whoNeeds: [
      { title: 'Secondary Property Owners', description: 'Homeowners maintaining seasonal or secondary residences.' },
      { title: 'Real Estate Investors', description: 'Investors with properties between tenants or awaiting sale.' },
      { title: 'Property Managers', description: 'Managers overseeing commercial or residential properties during vacancy.' },
    ],
    costFactors: [
      'Duration of vacancy',
      'Geographic location',
      'Property value',
      'Current property condition',
    ],
    faqs: [
      { question: 'When does a property need vacant insurance?', answer: 'Properties that have been vacant for more than 30 days may no longer be covered under a standard homeowner\'s policy and need separate vacant property coverage.' },
      { question: 'Can I add this to my existing policy?', answer: 'Coverage can sometimes be added to existing policies, though some insurers require a separate policy for vacant properties.' },
      { question: 'How is eligibility determined?', answer: 'Eligibility depends on the duration of vacancy, property condition, location, and the specific insurer\'s guidelines.' },
    ],
    relatedSlugs: ['builders-risk', 'rental-dwelling', 'homeowners'],
    seoTitle: 'Vacant & Unoccupied Property Insurance in North Carolina',
    seoDescription: 'Protect your vacant or unoccupied property with specialized insurance from BlackArrow Insurance. Coverage for damage, vandalism, and liability.',
  },
  // ── NC-targeted landing pages (Ahrefs SEO: high-CPC low-KD opportunities) ──
  {
    slug: 'workers-compensation-north-carolina',
    title: 'Workers Compensation Insurance in North Carolina',
    shortTitle: 'Workers Comp (NC)',
    category: 'commercial',
    tagline: 'Required NC coverage — sourced across 20+ carriers',
    description: 'Workers compensation insurance for North Carolina businesses, required by law for most employers with three or more employees. BlackArrow Insurance shops 20+ carriers to find NC-compliant coverage at the right price for your industry, from construction to healthcare to retail.',
    icon: 'shield',
    coverageTypes: [
      { title: 'Medical Expense Coverage', description: 'Pays for emergency care, hospitalization, physical therapy, and prescriptions for work-related injuries and illnesses.' },
      { title: 'Lost Wages Replacement', description: 'Replaces a portion of wages while an injured NC employee recovers and can\'t return to work — required by the NC Industrial Commission.' },
      { title: 'Disability Benefits', description: 'Temporary total, temporary partial, permanent partial, and permanent total disability benefits per NC statute.' },
      { title: 'Death Benefits', description: 'Funeral expenses and dependent benefits in the tragic event of a fatal workplace accident.' },
      { title: 'Employer Liability', description: 'Protects your business against lawsuits alleging negligence, gross negligence, or third-party-over claims.' },
    ],
    whoNeeds: [
      { title: 'NC Employers with 3+ Employees', description: 'Required by North Carolina law — sole proprietors and partnerships with three or more employees must carry workers comp.' },
      { title: 'Construction Contractors', description: 'Required regardless of employee count if you have even one employee. Certificates of insurance frequently requested by general contractors and clients.' },
      { title: 'Healthcare, Retail, Hospitality', description: 'Industries with elevated injury rates benefit from comprehensive coverage beyond the NC minimum.' },
    ],
    costFactors: [
      'Employee classification codes (e.g., roofers price higher than clerical)',
      'Total annual payroll',
      'Experience modification rate (e-mod) — your claims history',
      'State — NC rates are generally moderate compared to coastal states with heavier storm exposure',
      'Safety programs and return-to-work policies',
    ],
    faqs: [
      { question: 'Is workers comp required in North Carolina?', answer: 'Yes — NC law requires workers comp coverage for most employers with three or more employees (including part-time), or any number of employees if they are in construction-related work. Penalties for noncompliance can include fines, stop-work orders, and personal liability for owners.' },
      { question: 'What are the penalties for not having workers comp in NC?', answer: 'Employers can face daily fines of $50–$100 per employee per day, criminal charges for willful noncompliance, and personal liability for injuries sustained by uninsured employees. The NC Industrial Commission actively audits coverage.' },
      { question: 'Does workers comp cover independent contractors?', answer: 'Generally no — but NC uses a multi-factor test to distinguish true independent contractors from misclassified employees. If the state reclassifies your contractors, you may owe retroactive premiums and penalties.' },
      { question: 'How quickly can BlackArrow get me quotes?', answer: 'Most NC workers comp quotes are back within 24–48 hours. We use 20+ carriers to match your classification codes and payroll to the best-priced policy.' },
    ],
    relatedSlugs: ['business-owners-package', 'general-liability', 'commercial-property'],
    seoTitle: 'NC Workers Compensation Insurance — Required Coverage for 3+ Employees',
    seoDescription: 'NC workers comp insurance for businesses with 3+ employees. BlackArrow Insurance shops 20+ carriers for contractors, healthcare, retail, and hospitality across Eastern North Carolina. Same-day quotes.',
  },
  {
    slug: 'boat-insurance-north-carolina',
    title: 'Boat Insurance in North Carolina',
    shortTitle: 'Boat Insurance (NC)',
    category: 'personal',
    tagline: 'Coverage for NC waters — Intracoastal, Pamlico, Albemarle, and offshore',
    description: 'Boat insurance for North Carolina boat owners — fishing boats, pontoons, sailboats, center consoles, and yachts. BlackArrow Insurance writes policies for NC-registered vessels on the Intracoastal Waterway, Pamlico Sound, Albemarle Sound, and offshore Atlantic waters, with proper hurricane-named-storm deductibles for coastal moorage.',
    icon: 'anchor',
    coverageTypes: [
      { title: 'Hull & Machinery Coverage', description: 'Covers physical damage to the boat itself from collision, grounding, fire, theft, vandalism, and named storms.' },
      { title: 'Liability Coverage', description: 'Protects you if you injure another person or damage their property while operating your NC-registered vessel.' },
      { title: 'Uninsured Boater Coverage', description: 'Covers injuries caused by another boater who has no insurance — common on busy summer weekends in NC waters.' },
      { title: 'Fuel Spill & Salvage Coverage', description: 'Pays for required environmental cleanup and professional salvage, which NC requires for covered incidents.' },
      { title: 'On-Water Towing', description: 'Coverage for emergency towing, fuel delivery, and jump-starts on Pamlico and Albemarle sounds or offshore.' },
      { title: 'Trailer & Equipment Coverage', description: 'Covers your boat trailer, motor, electronics, and safety gear on and off the water.' },
    ],
    whoNeeds: [
      { title: 'Fishing Boat Owners', description: 'From Intracoastal flats boats to offshore sportfishers — coverage scaled to NC-specific risks.' },
      { title: 'Pontoon & Runabout Owners', description: 'Lake Waccamaw, Lake Gaston, and Falls Lake operators needing liability and damage protection.' },
      { title: 'Coastal Moorage Owners', description: 'Hurricane-named-storm deductibles and haul-out allowances for vessels moored in Eastern NC marinas.' },
    ],
    costFactors: [
      'Boat value, age, length, and horsepower',
      'Where the vessel is used and stored (coastal NC prices higher than inland lakes)',
      'Operator experience and boating safety course completion',
      'Hurricane deductible election — higher deductibles lower premiums for coastal owners',
      'Claims history and U.S. Coast Guard violations',
    ],
    faqs: [
      { question: 'Is boat insurance required in North Carolina?', answer: 'North Carolina does not mandate boat insurance by law, but it\'s required by most marinas, NC-lakefront HOAs, and lenders. We strongly recommend coverage for any vessel — liability claims from NC waterway collisions can easily exceed $100,000.' },
      { question: 'Do I need a separate hurricane-named-storm deductible?', answer: 'Yes — standard NC boat policies include a separate named-storm deductible for any tropical storm, hurricane, or tropical depression. Deductibles run 2–10% of hull value. Higher deductibles significantly lower your annual premium.' },
      { question: 'Does the policy cover me in other states?', answer: 'Most NC boat policies cover U.S. inland and coastal waters by default. Extended cruising to Florida, the Bahamas, or Canadian waters may require an endorsement — ask your BlackArrow agent before departing.' },
      { question: 'Am I covered during transport on I-95 or Hwy 17?', answer: 'Yes — trailer-towed transport damage is typically covered. Verify your coverage limits match your boat\'s current value before long hauls.' },
    ],
    relatedSlugs: ['auto', 'homeowners', 'life'],
    seoTitle: 'NC Boat Insurance — Intracoastal, Pamlico Sound & Offshore Coverage',
    seoDescription: 'NC boat insurance for Intracoastal, Pamlico Sound, Albemarle Sound, and offshore Atlantic waters. BlackArrow writes coastal NC policies with proper hurricane-named-storm deductibles. Fast quotes.',
  },
  {
    slug: 'auto-insurance-greenville-nc',
    title: 'Auto Insurance in Greenville, NC',
    shortTitle: 'Auto (Greenville NC)',
    category: 'personal',
    tagline: 'NC minimum limits, maximum carrier choice in Pitt County',
    description: 'Auto insurance for Greenville, NC drivers. BlackArrow Insurance is based at 905 Conference Drive in Greenville and shops 20+ carriers to match Pitt County drivers — ECU commuters, healthcare workers, families, and retirees — to the right liability limits, collision, and comprehensive coverage for NC roads.',
    icon: 'car',
    coverageTypes: [
      { title: 'Liability Coverage (NC Minimum)', description: 'North Carolina requires $30k/$60k bodily injury and $25k property damage minimums. BlackArrow helps Greenville drivers pick the right limits above the state floor.' },
      { title: 'Collision Coverage', description: 'Pays for damage to your vehicle from collisions with other cars or objects — required by most Greenville lenders.' },
      { title: 'Comprehensive Coverage', description: 'Covers theft, vandalism, fallen tree limbs, deer strikes (common on NC-33 and NC-43), and hurricane flooding.' },
      { title: 'Uninsured/Underinsured Motorist', description: 'NC requires UM/UIM coverage. Critical in Pitt County where a meaningful share of drivers carry only state-minimum limits.' },
      { title: 'Medical Payments / PIP', description: 'Covers medical expenses for you and your passengers after an accident, regardless of fault.' },
      { title: 'Rental Reimbursement & Roadside', description: 'Rental car while yours is in the shop; towing to a Greenville-area body shop.' },
    ],
    whoNeeds: [
      { title: 'ECU Students & Faculty', description: 'Commuters from Winterville, Ayden, and Farmville need liability limits scaled to NC-43 and 10th Street traffic.' },
      { title: 'ECU Health & Vidant Employees', description: 'Shift workers driving home late — comprehensive coverage matters.' },
      { title: 'Greenville Families', description: 'Multi-vehicle households benefit from BlackArrow\'s multi-policy discounts across 20+ carriers.' },
    ],
    costFactors: [
      'Greenville ZIP code (27834 vs. 27858 price differently)',
      'Driving record and NC DMV points',
      'Vehicle age, safety features, and anti-theft equipment',
      'Annual mileage — commuters to ECU or ECU Health price differently than low-mileage retirees',
      'Credit-based insurance score (NC allows this factor)',
      'Deductible choices',
    ],
    faqs: [
      { question: 'What are the NC minimum auto insurance requirements?', answer: 'North Carolina requires $30,000 bodily injury per person, $60,000 per accident, $25,000 property damage, plus uninsured motorist coverage. BlackArrow typically recommends 100/300/100 for most Greenville drivers for adequate protection.' },
      { question: 'Can I get SR-22 filings through BlackArrow?', answer: 'Yes — we work with carriers that file SR-22s with the NC DMV for drivers who\'ve had DWI convictions, license suspensions, or high-risk driving records.' },
      { question: 'Do you offer good-student or ECU-student discounts?', answer: 'Many of our carriers offer good-student discounts for full-time students (including ECU undergrads and graduate students) with a 3.0 GPA or higher. Ask us to check — the discount can be significant.' },
      { question: 'How fast can I get a Greenville quote?', answer: 'Most auto quotes are back same-day. Stop by 905 Conference Drive Suite 2B or request online.' },
    ],
    relatedSlugs: ['homeowners', 'life', 'boat'],
    seoTitle: 'Auto Insurance in Greenville, NC — Car Insurance for Pitt County',
    seoDescription: 'Greenville NC auto insurance from BlackArrow Insurance at 905 Conference Drive. We shop 20+ carriers for ECU students, healthcare workers, and Pitt County families. Same-day quotes.',
  },
];

export const insuranceHeroImages: Record<string, string> = {
  homeowners: '/images/insights/first-time-homebuyers-guide-to-homeowners-insurance.png',
  auto: '/images/insights/do-you-need-gap-insurance-when-its-essential-and-when-to-skip-it.png',
  life: '/images/insights/term-life-vs-whole-life-a-comprehensive-comparison.png',
  boat: '/images/insights/boat-insurance-for-new-boat-owners-what-you-need-to-know-before-hitting-the-water.png',
  'rental-dwelling': '/images/insights/how-rental-dwelling-insurance-differs-from-homeowners-insurance.png',
  'dump-straight-truck': '/images/insights/collision-vs-comprehensive-which-coverage-do-you-need-for-your-dump-truck.png',
  'commercial-auto': '/images/insights/how-your-commercial-auto-insurance-can-protect-against-lawsuits.png',
  'general-liability': '/images/insights/how-much-general-liability-insurance-coverage-does-your-business-really-need.png',
  'cyber-liability': '/images/insights/the-top-5-cybersecurity-threats-and-how-cyber-liability-insurance-can-protect-you.png',
  equipment: '/images/insights/how-equipment-breakdown-coverage-can-save-your-business-money.png',
  'business-owners-package': '/images/insights/what-types-of-businesses-benefit-most-from-business-owners-package-insurance.png',
  'workers-compensation': '/images/insights/how-workers-compensation-insurance-benefits-both-employers-and-employees.png',
  'commercial-property': '/images/insights/whats-covered-under-a-commercial-property-insurance-policy-a-detailed-breakdown.png',
  'short-term-rental': '/images/insights/homeowners-insurance-vs-short-term-rental-insurance-why-you-need-both.png',
  'long-term-rental': '/images/insights/do-you-need-long-term-rental-insurance-if-youre-renting-out-a-single-unit.png',
  'builders-risk': '/images/insights/how-builders-risk-insurance-can-protect-your-construction-site-from-unexpected-risks.png',
  'vacant-unoccupied': '/images/insights/5-risks-of-leaving-your-property-vacant-without-insurance-coverage.png',
};

export function getInsuranceHeroImage(slug: string): string {
  return insuranceHeroImages[slug] || '/images/AdobeStock_315458621.jpeg';
}

export function getInsuranceBySlug(slug: string): InsurancePage | undefined {
  return insurancePages.find(p => p.slug === slug);
}

export function getInsuranceByCategory(category: InsurancePage['category']): InsurancePage[] {
  return insurancePages.filter(p => p.category === category);
}

export const personalInsurance = insurancePages.filter(p => p.category === 'personal');
export const commercialInsurance = insurancePages.filter(p => p.category === 'commercial');
export const propertyInsurance = insurancePages.filter(p => p.category === 'property');

export const carriers = [
  'Progressive', 'Travelers', 'Hartford', 'Liberty Mutual', 'Safeco',
  'Heritage', 'Universal', 'National General', 'NCJUA', 'Hagerty',
  'Halifax Mutual', 'Foremost', 'Johnson & Johnson', 'Tower Hill',
  'SageSure', 'Orion 180', 'Orchid', 'JM Wilson', 'FM', 'CAB',
];
